[package]
name = "habitat-admission"
version = "0.1.0"
description = "habitat admission controller"
edition = "2021"
license = "Apache-2.0"
authors = ["ZhengYu Xu <zen-xu@outlook.com>"]
repository = "https://github.com/zen-xu/habitat"

[dependencies]
