blank_lines_upper_bound = 2
comment_width = 110
fn_single_line = true
imports_granularity = "Crate"
inline_attribute_width = 80
max_width = 110
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
