name: devcontainer

# When a pull request is opened that changes the Devcontainer configuration,
# ensure that the container continues to build properly.
on:
  pull_request:
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer.yml
  push:
    branches:
      - main
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer.yml

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.repository_owner == 'zen-xu' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
        if: github.ref == 'refs/heads/main'

      - name: Check devcontainer
        run: docker build .devcontainer
        if: github.ref != 'refs/heads/main'

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: zenxu/habitat-devcontainer:latest
          context: ".devcontainer"
        if: github.ref == 'refs/heads/main'
